CREATE DATABASE STUDIO
GO
USE STUDIO
GO

CREATE TABLE NHANVIEN(
	ID_NV INT IDENTITY(1,1) PRIMARY KEY,
	MaNV NVARCHAR(10) UNIQUE NOT NULL,
	TenNV text NOT NULL,
	DIACHI text NOT NULL,
	SDT VARCHAR(10) NOT NULL,
	NGAYNHAN DATE NOT NULL,
	Luong FLOAT NOT NULL,
	pass varchar(50) not null,
	vaitro bit not null
)

SELECT * FROM NHANVIEN
INSERT INTO NHANVIEN VALUES ('KyDV',N'Đặng Vĩnh Kỳ',N'Châu Phú - An Giang','0836484927','2023-08-08',8000, '123', 1)
INSERT INTO NHANVIEN VALUES ('TrieuMT',N'Nguyễn Minh Triệu',N'Ninh Kiều - Cần Thơ','0365836248','2023-09-25',9000, '123', 0)
INSERT INTO NHANVIEN VALUES ('DayNV',N'Nguyễn Vũ Đầy',N'An Phú - An Giang','0898758894','2023-03-19',8800, '123', 1)

CREATE TABLE KHACHHANG(
	ID_KhachHang INT IDENTITY(1,1) PRIMARY KEY,
	MaKH VARCHAR(10) UNIQUE NOT NULL,
	TenKH text NOT NULL,
	DIACHI text NOT NULL,
	SDT VARCHAR(10) NOT NULL,
	GioiTinh Bit not null,
)

CREATE TABLE HOADON (
	ID_HOADON INT IDENTITY PRIMARY KEY,
	MaHD VARCHAR(10) UNIQUE NOT NULL,
	Ngay Date NOT NULL,
	ThanhToan FLOAT NOT NULL,
	DIACHI text NOT NULL,
	ID_KhachHang INT NOT NULL,
	ID_NV INT NOT NULL,
	FOREIGN KEY(ID_KhachHang) REFERENCES KHACHHANG(ID_KhachHang),
	FOREIGN KEY(ID_NV) REFERENCES NHANVIEN(ID_NV),
)

CREATE TABLE SANPHAM(
	ID_SANPHAM INT IDENTITY PRIMARY KEY,
	MaSP VARCHAR(10) UNIQUE NOT NULL,
	TenSP text NOT NULL,
	ThuongHieu text NOT NULL,
	LoaiSP text NOT NULL,
	GiaDichVu FLOAT NOT NULL,
	MOTA text NOT NULL,
	DichVu text NOT NULL,
	ID_NV INT NOT NULL,
	FOREIGN KEY(ID_NV) REFERENCES NHANVIEN(ID_NV)
)

CREATE TABLE HDCT(
	MaHDCT VARCHAR(10) PRIMARY KEY,
	ID_HOADON INT NOT NULL,
	ID_SANPHAM INT NOT NULL,
	FOREIGN KEY(ID_HOADON) REFERENCES HOADON(ID_HOADON),
	FOREIGN KEY(ID_SANPHAM) REFERENCES SANPHAM(ID_SANPHAM),
)

SELECT * FROM KHACHHANG
INSERT INTO KHACHHANG VALUES ('KH01',N'Lê Văn An',N'Ô Môn - Cần Thơ','0909223323',0)
INSERT INTO KHACHHANG VALUES ('KH02',N'Lê Thị Chu',N'Ninh Kiều, Cần Thơ','0909133133',1)
INSERT INTO KHACHHANG VALUES ('KH03',N'Lê Văn Anh',N'Thốt Nốt, Cần Thơ','0909123153',0)
INSERT INTO KHACHHANG VALUES ('KH04',N'Lê Thị Thắm',N'Thới Bình, Cà Mau','0909143123',1)
INSERT INTO KHACHHANG VALUES ('KH05',N'Nguyễn Văn Lâm ',N'Long Xuyên, An Giang','0909123323',0)
INSERT INTO KHACHHANG VALUES ('KH06',N'Huỳnh Thị Thu',N'Hồng Dân, Bạc Liêu','0909223789',1)