package utilities;



import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;


import com.aspose.pdf.Color;
import com.aspose.pdf.Document;
import com.aspose.pdf.Element;
import com.aspose.pdf.Font;
import com.aspose.pdf.FontRepository;
import com.aspose.pdf.Page;
import com.aspose.pdf.Position;
import com.aspose.pdf.TextBuilder;
import com.aspose.pdf.TextFragment;
import com.aspose.pdf.drawing.GradientAxialShading;

public class Test {

	private static final String FILE_NAME = "/tmp/itext.pdf";

	public static void main(String[] args) {
		Document document = new Document();

		// Add page
		Page page = document.getPages().add();

		// Create text fragment
		TextFragment textFragment = new TextFragment(
				"Text 1: We have now applied text formatting. This is PDF generated by Aspose.PDF for .NET");
		textFragment.setPosition(new Position(100, 700));
		TextFragment textFragment1 = new TextFragment(
				"Text 2: We have now applied text formatting. This is PDF generated by Aspose.PDF for .NET");
		textFragment1.setPosition(new Position(100, 600));

		// Set text properties
		textFragment.getTextState().setFontSize(12);
		textFragment.getTextState().setFont(FontRepository.findFont("TimesNewRoman"));
		textFragment.getTextState().setBackgroundColor(Color.getLightGray());
		textFragment.getTextState().setForegroundColor(Color.getRed());

		textFragment1.getTextState().setDrawTextRectangleBorder(true);
		textFragment1.getTextState().setUnderline(true);
		textFragment1.getTextState().setStrikeOut(true);

		// Create new color with pattern colorspace
		Color color = new Color();
		color.setPatternColorSpace(new GradientAxialShading(Color.getRed(), Color.getBlue()));
		textFragment1.getTextState().setForegroundColor(color);

		// Create TextBuilder object
		TextBuilder textBuilder = new TextBuilder(page);

		// Append the text fragments to the PDF page
		textBuilder.appendText(textFragment);
		textBuilder.appendText(textFragment1);

		// Save the PDF document
		document.save("Generated-PDF.pdf");
	}

//	public static void main(String[] args) {
//		Scanner sc = new Scanner(System.in);
//		String input = sc.nextLine();
//		int max = 100;
//		System.out.println(AutoString.autoID(input, max));
//	
//		System.out.println(input +(String.format("%04d", max)));

//		System.out.println(input.replaceAll(" ", ""));
//		String[] output = input.split(" ");
//		System.out.println(output[2]);
//		
//		String kho = "";
//		for (int i = 0; i < output.length - 1; i++) {
//			
//			kho += output[i].substring(0, 1);
//			
//		}
//		System.out.println(kho);

	// System.out.println(AutoString.autoEmail("Nguyen Minh Trieu"));

//		int code = (int) Math.floor(((Math.random() * 899999) + 100000));
//		System.out.println(code);

//		Email email = new Email();
//		System.out.println(email.messageMail);
//		System.out.println(email.messageMail);

//		Connection conn = JDBCUtil.getConnection();
//		int id = 0;
//		try {
//			PreparedStatement pst = conn.prepareStatement("SELECT Max(MaKH) as LastID FROM KHACHHANG");
//			ResultSet rs = pst.executeQuery();
//			String makh = "";
//			while(rs.next()) {
//				makh += rs.getString(1);
//			}
//			
//			System.out.println(makh);
//			
//			String[] split = makh.split("000");
//			for (int i = 1; i < split.length; i++) {
//				id = Integer.parseInt(split[i]);
//				
//			}
//			pst.close();
//			rs.close();
//			conn.close();
//		} catch (SQLException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
//		
//		System.out.println(String.format("%04d", id + 1));

//		NhanVienModel model = new NhanVienModel("KyDV", null, null, null, null, null, false, false);
//		INhanVien.getInstance().selectByID(model);

//		DecimalFormat d = new DecimalFormat("###,##0.000");
//		System.out.println(d.format(scanner.nextDouble()));

//	}

}
